# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:title/
socials:
    github: https://github.com/The-Aether-Team
    modrinth: https://modrinth.com/user/The-Aether-Team
    curseforge: https://www.curseforge.com/members/theaetherteam
    wikigg: https://aether.wiki.gg/
    bluesky: https://bsky.app/profile/aether-mod.net
    twitter: https://twitter.com/DevAether
    mastodon: https://mastodon.gamedev.place/@DevAether
    facebook: https://www.facebook.com/AetherMod
    threads: https://www.threads.net/@devaether
    instagram: https://www.instagram.com/devaether
    reddit: https://www.reddit.com/r/TheAether/
    youtube: https://www.youtube.com/GildedGames
    twitch: https://twitch.tv/theaetherteam
    tiktok: https://www.tiktok.com/@devaether
markdown: kramdown
paginate: 5
paginate_path: "blog/:num/"
date_format: "%b %-d, %Y"
# UNCHANGEABLE
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge

# Build settings
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
